
package org.aperteworkflow.samples.application.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2015-08-03T11:57:56.193+02:00
 * Generated source version: 2.4.4
 * 
 */
public final class RegisterApplicationService_IncidentSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.aperteworkflow.org/samples/", "RegisterApplicationService");

    private RegisterApplicationService_IncidentSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegisterApplicationService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegisterApplicationService_Service ss = new RegisterApplicationService_Service(wsdlURL, SERVICE_NAME);
        RegisterApplicationService port = ss.getIncidentSOAP();
        
        {
        System.out.println("Invoking registerApplication...");
        RegisterApplicationRequestType _registerApplication_name = null;
        RegisterApplicationResponseType _registerApplication__return = port.registerApplication(_registerApplication_name);
        System.out.println("registerApplication.result=" + _registerApplication__return);


        }

        System.exit(0);
    }

}
