package org.aperteworkflow.samples.application.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2015-08-03T11:57:56.239+02:00
 * Generated source version: 2.4.4
 * 
 */
@WebServiceClient(name = "RegisterApplicationService", 
                  wsdlLocation = "file:/C:/home/aperte/aperte-workflow-core-fork/samples/application-ws-schema/src/main/resources/org/aperteworkflow/samples/service/RegisterApplication.wsdl",
                  targetNamespace = "http://www.aperteworkflow.org/samples/") 
public class RegisterApplicationService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.aperteworkflow.org/samples/", "RegisterApplicationService");
    public final static QName IncidentSOAP = new QName("http://www.aperteworkflow.org/samples/", "incidentSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/home/aperte/aperte-workflow-core-fork/samples/application-ws-schema/src/main/resources/org/aperteworkflow/samples/service/RegisterApplication.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegisterApplicationService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/home/aperte/aperte-workflow-core-fork/samples/application-ws-schema/src/main/resources/org/aperteworkflow/samples/service/RegisterApplication.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegisterApplicationService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegisterApplicationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterApplicationService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegisterApplicationService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegisterApplicationService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegisterApplicationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RegisterApplicationService
     */
    @WebEndpoint(name = "incidentSOAP")
    public RegisterApplicationService getIncidentSOAP() {
        return super.getPort(IncidentSOAP, RegisterApplicationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterApplicationService
     */
    @WebEndpoint(name = "incidentSOAP")
    public RegisterApplicationService getIncidentSOAP(WebServiceFeature... features) {
        return super.getPort(IncidentSOAP, RegisterApplicationService.class, features);
    }

}
